### ISSUE TITLE
PHP Warning:  stream_socket_accept(): accept failed: Operation timed out

### ISSUE THREAD

**Issue by 0plus1** [ddelnano/dredd-hooks-php#42]
Hi,

I am having an issue I cannot seem to figure out, related to: #26 

```
/redacted/.bin/dredd --config=./tests/dredd/hooks/dredd.yml
warn: Error connecting to the hooks handler process. Is the handler running? Retrying.
error: Connection timeout 1.5s to hooks handler on 127.0.0.1:61321 exceeded. Try increasing the limit.
error Command failed with exit code 1.
```

Following steps found in different threads here, I launched the server manually:

```
vendor/bin/dredd-hooks-php --force
Starting server
PHP Warning:  stream_socket_accept(): accept failed: Operation timed out in /redacted/vendor/ddelnano/dredd-hooks-php/src/Server.php on line 39

Warning: stream_socket_accept(): accept failed: Operation timed out in /redacted/vendor/ddelnano/dredd-hooks-php/src/Server.php on line 39
```

I do not understand what is going on here, it's a pretty cryptic message, does this mean that the port is in use?

I am running in a local environment, with laravel + valet as a server.

My yml:

```
color: true
dry-run: null
hookfiles: ./tests/dredd/hooks/hookfile.php
language: vendor/bin/dredd-hooks-php
require: null
server: 'php -S localhost:3000 -t public/'
server-wait: 3
init: false
custom:
  apiaryApiKey: ''
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./documentation/blueprint/api-description.apib
endpoint: 'http://localhost:3000/v1/'
```

Thanks for any help

**Comment by ddelnano** [comment]
> I do not understand what is going on here, it's a pretty cryptic message, does this mean that the port is in use?

The server was able to start, however, the error you are seeing indicates that no client attempted to make a connection to it. That's expected behavior unless you were trying to open a tcp socket to that port *while* running that command.

Have you tried increasing `hooks-worker-connect-timeout`? 1.5 seconds should be enough but I would try that first. If that doesn't help I would probably use a combination of [netstat](https://linux.die.net/man/8/netstat) to verify that the hooks server is bound to the correct port and [strace](https://linux.die.net/man/1/strace) to see where dredd is connecting to debug this further.

**Comment by ddelnano** [comment]
I'm happy to help you through this more but I'm going to close to issue for now.
