### ISSUE TITLE
How can the hooks output information

### ISSUE THREAD

**Issue by MCMic** [ddelnano/dredd-hooks-php#43]
When using echo or print_r in the hooks it does not get printed to the output.

Is there any way to get the hooks output?

**Comment by ddelnano** [comment]
You need to enable debug logging in dredd and then you should see the stdout and stderr. See [this](https://github.com/apiaryio/dredd/blob/master/lib/HooksWorkerClient.js#L190-L191).

I'm happy to talk through this with you but I'm going to close this because it isn't actually an issue with the php hooks.

**Comment by MCMic** [comment]
It would help if the readme stated this.

The examples in dredd documentation for PHP hooks are using echo so it’s surprising to the user when the output is not there.

**Comment by rask** [comment]
What worked for me:

1. Call `dredd` as usual, but add `-l debug` argument
2. `file_put_contents('php://stderr', 'my message');`

Though this seemed to be quite flaky, and did not output as much as I expected it to. Need to investigate.
